data:
  raw: data/sample.csv
  processed_cleaned: data/processed/cleaned.csv
  features_train: data/processed/train_features.csv
  features_test: data/processed/test_features.csv
  labels_train: data/processed/train_labels.csv
  labels_test: data/processed/test_labels.csv

models:
  linear_model_r: models/linear_model.rds
  linear_model_py: models/linear_model.pkl
  random_forest_model: models/random_forest.pkl
  diagnostics_report: models/diagnostics.txt

results:
  validation_metrics: results/validation_metrics.csv
  plots: results/figures/

logs:
  training_log: logs/train.log
  validation_log: logs/validate.log
