run:
  name: example

paths:
  root_path: ~/example-repo

model:
  path: /mnt/warsaw/fire/collab-test/sample-model
  iteration:
    - run_id: run_001
      start_year: 2015
      end_year: 2016
      scenario: baseline
    - run_id: run_002
      start_year: 2020
      end_year: 2021
      scenario: hot_dry
    - run_id: run_003
      start_year: 2030
      end_year: 2035
      scenario: future_risk

data:
  raw: /mnt/warsaw/fire/collab-test/sample.csv
