name: example
channels:
  - conda-forge
  - defaults
  - r

dependencies:
  # Python runtime & packages
  - python=3.10
  - pandas
  - scikit-learn
  - pyyaml

  # R runtime & packages
  - r-base=4.2
  - r-yaml
  - r-here

  # CLI tool for shell scripts
  - yq # not to be confused with the python package "yq"