name: example
channels:
  - conda-forge
  - defaults
  - r

dependencies:
# Python dependencies
  - python==3.11
  - gdal==3.6
  - rasterio
  - geopandas
  - shapely
  - pip
  - pip:
      - pyyaml

# R base and packages
  - r-base=4.2
  - r-tidyverse
  - r-data.table
  - r-yaml
  - r-here
  - r-ggplot2
  - r-devtools
  - r-remotes
  - r-rmarkdown

# shell tools
  - yq # not to be confused with the python package "yq"