name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Conda with caching
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: false
          activate-environment: example-test
          environment-file: config/environment.yaml
          use-mamba: true
          cache-environment: true

      - name: Confirm environment is ready
        shell: bash -l {0}
        run: |
          which Rscript
          which python
          conda list
          make train DATA_MODE=test
